### ISSUE TITLE
config.tomlを渡すオプションを追加する

### ISSUE THREAD

**Issue by uzulla** [uzulla/MyOhAdmin#3]
OpenHandsのサンドボックスコンテナの設定をおこなう `config.toml` について渡せると有用そうなので検討する。

status dirは既存で確定するので、そこに設置してbindするのがよいだろうか？

### OpenHands の `config.toml` 設定ガイド

- 設定ファイルの配置方法と情報源
- 基本的な設定サンプル
- Docker で起動する際の `config.toml` の渡し方（バインド方法）

#### 📚 情報源

OpenHands の `config.toml` に関する情報は以下のページに記載されています：

- [https://docs.all-hands.dev/modules/usage/installation](https://docs.all-hands.dev/modules/usage/installation)
- リポジトリ内 `config.template.toml`

#### 🛠️ 基本的な `config.toml` の設定サンプル

```toml
[core]
# セッション開始時に自動実行されるコマンド
runtime_extra_deps = """
# Gitの設定
git config --global user.name "Your Name"
git config --global user.email "your.email@example.com"

# APTの非対話モード設定とインストール
export DEBIAN_FRONTEND=noninteractive
echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90assumeyes
apt-get update && apt-get install -y curl git

# 任意のリポジトリのクローン
git clone https://github.com/example/repo.git /workspace/repo
"""

# 環境変数の設定
runtime_startup_env_vars = { DEBIAN_FRONTEND = "noninteractive" }
```

#### Dockerに渡す方法

```
docker run \
  -v $(pwd)/config.toml:/app/config.toml \
  -p 3000:3000 \
  allhands/openhands
```

*config.toml を変更した後は、コンテナの再起動が必要です*
